### PR TITLE
Implement pH Charging Functionality for SMILES Input

### PR DESCRIPTION
**Pull request by johlys**
Implemented the pH charger script as described in issue #4. Currently, you can input one or multiple SMILES strings, select the "Charge SMILES with pH" option, and then specify the pH value and range.

### Example of use
Using 'CCN' as input:
bilde

Output:
bilde

### CODE REVIEW

**Comment by kjemist** [comment]
Okay, this looks correct.

I tested CalcMolDescriptors() locally in RDKit, and it does output sensible descriptors for CC[NH3+]. If you can now add the function so that descriptors is calculated for CC[NH3+] as well as CCN, I believe we can merge this.

**Comment by johlys** [comment]
> I tested CalcMolDescriptors() locally in RDKit, and it does output sensible descriptors for CC[NH3+]. If you can now add the function so that descriptors is calculated for CC[NH3+] as well as CCN, I believe we can merge this.

So when you select "Charge smiles with pH" as well as some other descriptors, the result should show the descriptors calculated on the charged version of the SMILES?

**Comment by kjemist** [comment]
Yes, calculated descriptors for both the uncharged and the charged version.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by kjemist — COMMENTED** [review]
Nice, this looks good. If you add a link to the Poetry docs in the ReadMe-file, I will approve this

**Comment by johlys** [comment]
Updated the readme. Downloaded CSV files will now also contain information about charged SMILES.

**Review by kjemist — APPROVED** [review]
Alright, this works for me.

Good job

**Pull request merged**
